In [11]:
import numpy as np
import cv2

In [12]:
img=cv2.imread('./data/friends.jpg')

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# Load cascade classifier
haar=cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [14]:
image=img.copy()
# step-1:convert image to grayskale
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# step-2: apply grayscale image to cascade classifier
face_rect=haar.detectMultiScale(gray,1.3,5)
# step-3:draw bounding box
for x,y,w,h in face_rect: 
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow('detected facec',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
print(face_rect)

[[256  88  98  98]
 [127 107  97  97]
 [405  90  99  99]]


### Real Time Face Detection using OpenCV  

In [22]:
cap =cv2.VideoCapture('./data/video.mp4')

while True:
    ret,frame=cap.read()
    if ret==False:
        break

    image=frame.copy()
    # step-1:convert image to grayskale
    gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    # step-2: apply grayscale image to cascade classifier
    face_rect=haar.detectMultiScale(gray,1.3,5)
    # step-3:draw bounding box
    for x,y,w,h in face_rect: 
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
        
    cv2.imshow('face detection',image)

    if cv2.waitKey(10)==27:
        break

cap.release()
cv2.destroyAllWindows()